services:
  api:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - database
    environment:
      - REDIS_ADDR=database:6379
  database:
    image: redis
    ports:
      - "6379:6379"